function ppm = get_fit_ppm(fitStruct)
%GET_FIT_PPM Robust extraction of peak ppm from fit structure.

    fields = { ...
        'ppm', ...
        'ppm0', ...
        'peakPPM', ...
        'peakPpm', ...
        'peak_ppm', ...
        'centerPPM', ...
        'centerPpm', ...
        'center_ppm', ...
        'center', ...
        'x0', ...
        'freqPPM', ...
        'freqPpm', ...
        'frequencyPPM', ...
        'frequencyPpm' ...
        };

    ppm = NaN;

    for i = 1:numel(fields)
        f = fields{i};
        if isfield(fitStruct, f)
            val = fitStruct.(f);
            if isnumeric(val) && isscalar(val)
                ppm = val;
                return;
            end
        end
    end

    disp('Available fit fields:');
    disp(fieldnames(fitStruct));
    error('Could not find ppm field in fit structure.');
end
